version: 2
updates:
  # Python dependencies (main project)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "onnwee"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    # Group patch updates to reduce PR noise
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "all"
    # Separate major version updates for careful review
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "onnwee"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
    versioning-strategy: increase
  
  # E2E test npm dependencies
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "testing"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
        update-types:
          - "minor"
          - "patch"
  
  # JavaScript SDK dependencies
  - package-ecosystem: "npm"
    directory: "/clients/javascript"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "sdk"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  
  # Root package.json (commitizen, husky, etc.)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "tooling"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  
  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "onnwee"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  
  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "github/*"
