# Sponsor button for GitHub mirrors of this repository.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button
custom: ["https://support.subcult.tv"]
