{{- if and .Values.api.enabled .Values.api.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "transcript-create.fullname" . }}-api
  labels:
    {{- include "transcript-create.api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "transcript-create.api.selectorLabels" . | nindent 6 }}
{{- end }}
{{- if and .Values.worker.enabled .Values.worker.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "transcript-create.fullname" . }}-worker
  labels:
    {{- include "transcript-create.worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "transcript-create.worker.selectorLabels" . | nindent 6 }}
{{- end }}
