blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/subculture-collective/transcript-create/discussions
    about: Ask questions, share ideas, or discuss the project with the community
  - name: 📚 Documentation
    url: https://github.com/subculture-collective/transcript-create#readme
    about: Check our comprehensive documentation for guides and API reference
  - name: 🔒 Security Vulnerability
    url: https://github.com/subculture-collective/transcript-create/security/advisories/new
    about: Report security vulnerabilities privately through GitHub Security Advisories
