import uuid
from typing import Literal, Union

from fastapi import APIRouter, Depends, Query, Response

from .. import crud
from ..db import get_db
from ..exceptions import TranscriptNotReadyError, VideoNotFoundError
from ..transcripts.blocks import FORMATTER_VERSION, build_transcript_blocks
from ..transcripts.merged import build_merged_transcript
from ..transcripts.youtube_formatting import build_youtube_caption_blocks, format_youtube_caption_text
from ..transcripts.service import TranscriptPresentationService
from ..transcripts.types import TranscriptSegment
from ..schemas import (
    CleanedTranscriptResponse,
    CleanupConfig,
    ErrorResponse,
    FormattedTranscriptResponse,
    PaginatedVideos,
    PageInfo,
    Segment,
    TranscriptBlockResponse,
    TranscriptResponse,
    VideoInfo,
    YouTubeTranscriptResponse,
    YTSegment,
)

router = APIRouter(prefix="", tags=["Videos"])
transcript_presentation_service = TranscriptPresentationService()


def _cleanup_config() -> CleanupConfig:
    return CleanupConfig(
        normalize_unicode=True,
        normalize_whitespace=True,
        remove_special_tokens=True,
        preserve_sound_events=False,
        add_punctuation=True,
        punctuation_mode="rule-based",
        add_internal_punctuation=True,
        capitalize=True,
        fix_all_caps=True,
        remove_fillers=True,
        filler_level=1,
        segment_sentences=False,
        merge_short_segments=False,
        min_segment_length_ms=1000,
        max_gap_for_merge_ms=500,
        speaker_format="structured",
        detect_hallucinations=True,
        language_specific_rules=True,
    )


def _block_response(block, include_merge_metadata: bool = False) -> TranscriptBlockResponse:
    payload = {
        "block_index": block.block_index,
        "start_ms": block.start_ms,
        "end_ms": block.end_ms,
        "speaker_label": block.speaker_label,
        "text": block.text,
        "segment_ids": block.segment_ids,
        "kind": block.kind,
        "formatter_version": getattr(block, "formatter_version", FORMATTER_VERSION),
    }
    if include_merge_metadata:
        payload.update(
            {
                "primary_source": block.primary_source,
                "supporting_sources": block.supporting_sources,
                "needs_review": block.needs_review,
                "merge_reason": block.merge_reason,
                "similarity": block.similarity,
            }
        )
    return TranscriptBlockResponse(**payload)


def _youtube_segments_for_merge(db, video_id: uuid.UUID) -> tuple[dict | None, list, list[TranscriptSegment]]:
    yt = crud.get_youtube_transcript(db, video_id)
    if not yt:
        return None, [], []
    rows = crud.list_youtube_segments(db, yt["id"])
    return yt, rows, [TranscriptSegment(start_ms=r[0], end_ms=r[1], text=r[2], speaker_label=None) for r in rows]


@router.get(
    "/videos/{video_id}/transcript",
    response_model=Union[TranscriptResponse, CleanedTranscriptResponse, FormattedTranscriptResponse],
    summary="Get video transcript",
    description="""
    Retrieve the Whisper-generated transcript for a video with optional speaker diarization.

    This endpoint returns the transcript generated by our Whisper pipeline, which includes
    speaker labels if diarization was successful.

    **Transcript Generation:**
    - Audio is transcribed using Whisper (faster-whisper or openai-whisper backend)
    - Optional speaker diarization using pyannote.audio
    - Segments are ordered chronologically by start time

    **Modes:**
    - `raw` (default): Returns raw Whisper-generated segments without any processing
    - `cleaned`: Returns segments with cleanup applied (filler removal, normalization, punctuation)
    - `formatted`: Returns fully formatted text with speaker labels and paragraph structure

    **Note:** Responses are cached per mode. ETags reflect the mode to avoid stale caches.
    """,
    responses={
        200: {"description": "Transcript retrieved successfully"},
        404: {
            "description": "Video not found",
            "model": ErrorResponse,
        },
        503: {
            "description": "Transcript not ready - still processing",
            "model": ErrorResponse,
            "content": {
                "application/json": {
                    "example": {
                        "error": "transcript_not_ready",
                        "message": "Transcript for video 123e4567-e89b-12d3-a456-426614174000 is still processing",
                        "details": {"state": "processing"},
                    }
                }
            },
        },
    },
)
def get_transcript(
    video_id: uuid.UUID,
    mode: Literal["raw", "cleaned", "formatted"] = Query(
        "raw",
        description="Transcript mode: raw (default), cleaned (with cleanup), or formatted (with paragraphs)",
    ),
    source: Literal["best", "merged", "whisper", "youtube"] = Query(
        "whisper",
        description="Transcript source policy: whisper (default), youtube, merged, or best (merged if both sources exist)",
    ),
    db=Depends(get_db),
    response: Response = None,
):
    """Get the Whisper-generated transcript for a video."""
    # Check if video exists
    video = crud.get_video(db, video_id)
    if not video:
        raise VideoNotFoundError(str(video_id))

    segs = crud.list_segments(db, video_id)
    segments = [transcript_presentation_service.from_db_row(r) for r in segs]
    yt, yt_segs, yt_segments_for_merge = _youtube_segments_for_merge(db, video_id) if source in ("best", "merged", "youtube") else (None, [], [])

    if source in ("best", "merged") and segments and yt_segments_for_merge:
        merged = build_merged_transcript(str(video_id), segments, yt_segments_for_merge)
        merged_segments = [
            Segment(start_ms=s.start_ms, end_ms=s.end_ms, text=s.text, speaker_label=s.speaker_label)
            for s in merged.segments
        ]
        if response:
            response.headers["ETag"] = f'"{video_id}-{mode}-merged"'
            response.headers["Cache-Control"] = "public, max-age=3600"
        if mode == "raw":
            return TranscriptResponse(
                video_id=video_id,
                segments=merged_segments,
                source="merged",
                source_label="Merged transcript",
            )
        blocks = [_block_response(block, include_merge_metadata=True) for block in merged.blocks]
        return FormattedTranscriptResponse(
            video_id=video_id,
            segments=merged_segments,
            text="\n\n".join(f"{block.speaker_label}:\n{block.text}" if block.speaker_label else block.text for block in blocks),
            format="structured",
            cleanup_config=_cleanup_config(),
            blocks=blocks,
            source="merged",
            source_label="Merged transcript",
        )

    if source == "youtube" or (source == "best" and not segs):
        if yt:
            yt_segments = [Segment(start_ms=r[0], end_ms=r[1], text=r[2], speaker_label=None) for r in yt_segs]
            rows = [(r[0], r[1], r[2]) for r in yt_segs]
            if response:
                response.headers["ETag"] = f'"{video_id}-{mode}-youtube"'
                response.headers["Cache-Control"] = "public, max-age=3600"
            if mode == "raw":
                return TranscriptResponse(
                    video_id=video_id,
                    segments=yt_segments,
                    source="youtube",
                    source_label="YouTube captions",
                )
            blocks = [
                _block_response(b)
                for b in build_youtube_caption_blocks(rows)
            ]
            return FormattedTranscriptResponse(
                video_id=video_id,
                segments=yt_segments,
                text=format_youtube_caption_text(rows),
                format="structured",
                cleanup_config=_cleanup_config(),
                blocks=blocks,
                source="youtube",
                source_label="YouTube captions",
            )
        if source == "youtube":
            raise TranscriptNotReadyError(str(video_id), "no_youtube_transcript")
    if not segs:
        # No segments found; inferring that the video is still processing
        raise TranscriptNotReadyError(str(video_id), "processing")

    # Set ETag based on mode and video_id for cache differentiation
    etag = f'"{video_id}-{mode}-whisper"'
    if response:
        response.headers["ETag"] = etag
        response.headers["Cache-Control"] = "public, max-age=3600"

    # Handle different modes
    if mode == "raw":
        return transcript_presentation_service.present_raw(video_id, segments)

    elif mode == "cleaned":
        return transcript_presentation_service.present_cleaned(video_id, segments)

    elif mode == "formatted":
        persisted_blocks = [
            block for block in crud.list_transcript_blocks(db, video_id) if block["formatter_version"] == FORMATTER_VERSION
        ]
        if persisted_blocks:
            blocks = [
                TranscriptBlockResponse(
                    block_index=r["block_index"],
                    start_ms=r["start_ms"],
                    end_ms=r["end_ms"],
                    speaker_label=r["speaker_label"],
                    text=r["text"],
                    segment_ids=r["segment_ids"],
                    kind=r["kind"],
                    formatter_version=r["formatter_version"],
                    primary_source="whisper",
                )
                for r in persisted_blocks
            ]
        else:
            blocks = [
                _block_response(b)
                for b in build_transcript_blocks(segments)
            ]

        formatted_text = "\n\n".join(
            f"{block.speaker_label}:\n{block.text}" if block.speaker_label else block.text for block in blocks
        )

        return FormattedTranscriptResponse(
            video_id=video_id,
            segments=[
                Segment(
                    start_ms=s.start_ms,
                    end_ms=s.end_ms,
                    text=s.text,
                    speaker_label=s.speaker_label,
                )
                for s in segments
            ],
            text=formatted_text,
            format="structured",
            cleanup_config=_cleanup_config(),
            blocks=blocks,
            source="whisper",
            source_label="Whisper transcript",
        )


@router.get(
    "/videos/{video_id}",
    response_model=VideoInfo,
    summary="Get video information",
    description="""
    Retrieve basic information about a video including title, duration, and YouTube ID.
    """,
    responses={
        200: {"description": "Video information retrieved successfully"},
        404: {"description": "Video not found", "model": ErrorResponse},
    },
)
def get_video_info(video_id: uuid.UUID, db=Depends(get_db)):
    """Get basic information about a video."""
    v = crud.get_video(db, video_id)
    if not v:
        raise VideoNotFoundError(str(video_id))
    return VideoInfo(**dict(v))


@router.get(
    "/videos",
    response_model=PaginatedVideos,
    summary="List videos",
    description="""
    List all videos with pagination support.

    Returns videos in reverse chronological order (newest first).
    """,
    responses={
        200: {
            "description": "List of videos retrieved successfully",
            "content": {
                "application/json": {
                    "example": {
                        "items": [
                            {
                                "id": "123e4567-e89b-12d3-a456-426614174000",
                                "youtube_id": "dQw4w9WgXcQ",
                                "title": "Example Video",
                                "duration_seconds": 212,
                                "has_whisper_transcript": True,
                                "has_youtube_transcript": False,
                            }
                        ],
                        "page_info": {
                            "has_next_page": False,
                            "has_previous_page": False,
                            "next_cursor": None,
                            "previous_cursor": None,
                            "total_count": 1,
                        },
                    }
                }
            },
        }
    },
)
def list_videos(
    limit: int = Query(50, ge=1, le=100, description="Maximum number of videos to return"),
    offset: int = Query(0, ge=0, description="Number of videos to skip for pagination"),
    q: str | None = Query(None, description="Search query for title, youtube ID, or channel name"),
    date_field: Literal["uploaded_at", "created_at", "updated_at"] = Query(
        "uploaded_at", description="Date field used for date filtering"
    ),
    date_from: str | None = Query(None, description="Inclusive YYYY-MM-DD date lower bound"),
    date_to: str | None = Query(None, description="Inclusive YYYY-MM-DD date upper bound"),
    completed_only: bool = Query(False, description="Only include completed videos that have transcript segments"),
    category: str | None = Query(None, description="Filter by video category/type"),
    db=Depends(get_db),
):
    """List all videos with pagination."""
    rows = crud.list_videos(
        db,
        limit=limit,
        offset=offset,
        q=q,
        date_field=date_field,
        date_from=date_from,
        date_to=date_to,
        completed_only=completed_only,
        category=category,
    )
    total_count = crud.count_videos(
        db,
        q=q,
        date_field=date_field,
        date_from=date_from,
        date_to=date_to,
        completed_only=completed_only,
        category=category,
    )
    items = [VideoInfo(**dict(r)) for r in rows]
    return PaginatedVideos(
        items=items,
        page_info=PageInfo(
            has_next_page=offset + len(items) < total_count,
            has_previous_page=offset > 0,
            next_cursor=str(offset + limit) if offset + len(items) < total_count else None,
            previous_cursor=str(max(0, offset - limit)) if offset > 0 else None,
            total_count=total_count,
        ),
    )


@router.get(
    "/videos/{video_id}/youtube-transcript",
    response_model=YouTubeTranscriptResponse,
    summary="Get YouTube's native captions",
    description="""
    Retrieve YouTube's native closed captions for a video.

    This endpoint returns the original captions provided by YouTube, either
    auto-generated (ASR) or manually created. These are separate from our
    Whisper-generated transcripts.

    **Caption Types:**
    - `asr`: Auto-generated by YouTube's speech recognition
    - Manual: Human-created closed captions
    """,
    responses={
        200: {"description": "YouTube transcript retrieved successfully"},
        404: {"description": "Video not found", "model": ErrorResponse},
        503: {
            "description": "YouTube transcript not available",
            "model": ErrorResponse,
        },
    },
)
def get_youtube_transcript(
    video_id: uuid.UUID,
    mode: Literal["raw", "formatted"] = Query("raw", description="Caption mode: raw or formatted"),
    db=Depends(get_db),
):
    """Get YouTube's native closed captions for a video."""
    # Check if video exists
    video = crud.get_video(db, video_id)
    if not video:
        raise VideoNotFoundError(str(video_id))

    yt = crud.get_youtube_transcript(db, video_id)
    if not yt:
        raise TranscriptNotReadyError(str(video_id), "no_youtube_transcript")

    segs = crud.list_youtube_segments(db, yt["id"])
    segments = [YTSegment(start_ms=r[0], end_ms=r[1], text=r[2]) for r in segs]
    blocks = []
    full_text = yt.get("full_text")

    if mode == "formatted":
        rows = [(r[0], r[1], r[2]) for r in segs]
        caption_blocks = build_youtube_caption_blocks(rows)
        blocks = [
            TranscriptBlockResponse(
                block_index=b.block_index,
                start_ms=b.start_ms,
                end_ms=b.end_ms,
                speaker_label=b.speaker_label,
                text=b.text,
                segment_ids=b.segment_ids,
                kind=b.kind,
                formatter_version=b.formatter_version,
            )
            for b in caption_blocks
        ]
        full_text = format_youtube_caption_text(rows)
    return YouTubeTranscriptResponse(
        video_id=video_id,
        language=yt.get("language"),
        kind=yt.get("kind"),
        full_text=full_text,
        segments=segments,
        blocks=blocks,
    )
