---
# Main playbook for full server setup
- name: Configure base system
  hosts: all
  become: yes
  roles:
    - base
  tags:
    - base

- name: Install Docker
  hosts: all
  become: yes
  roles:
    - docker
  tags:
    - docker

- name: Install GPU drivers
  hosts: workers
  become: yes
  roles:
    - gpu-drivers
  when: install_gpu_drivers | default(false)
  tags:
    - gpu
    - gpu-drivers

- name: Deploy application
  hosts: all
  become: yes
  roles:
    - app
  tags:
    - app
    - deploy

- name: Setup monitoring
  hosts: all
  become: yes
  roles:
    - monitoring
  when: install_monitoring | default(false)
  tags:
    - monitoring
